% Example usage of the DNAm Network Clock (MATLAB).
%
% Run it from the repository root:
%
%     >> example
%
% Or copy these commands into your own script. The "weights" folder is found
% automatically when predict_age.m sits in matlab/ next to ../weights. If you
% move predict_age.m elsewhere, pass the weights path as a third argument:
% predict_age(betas, cpgs, '/path/to/weights').

addpath('matlab');

% ---- The few lines that matter for your own data ----
% betas must be samples (rows) x CpGs (columns), with cpg_ids naming the columns.
T = readtable(fullfile('examples', 'example_input.csv'), ...
              'ReadRowNames', true, 'VariableNamingRule', 'preserve');
cpg_ids = T.Properties.VariableNames;
betas   = table2array(T);
ages    = predict_age(betas, cpg_ids);
% ------------------------------------------------------

fprintf('Loaded reference input: %d samples x %d CpGs\n', ...
        size(betas, 1), size(betas, 2));
fprintf('Predictions:\n');
fprintf('  range  : %.2f to %.2f years\n', min(ages), max(ages));
fprintf('  median : %.2f years\n', median(ages));

% Check against the stored reference predictions (generated by the Python code).
expected = readtable(fullfile('examples', 'expected_output.csv'));
max_diff = max(abs(ages - expected.predicted_age));
if max_diff < 1e-6
    fprintf('\n  max |predicted - expected| = %.2e   PASS\n', max_diff);
else
    fprintf('\n  max |predicted - expected| = %.2e   FAIL\n', max_diff);
end
