# Example usage of the DNAm Network Clock (R).
#
# Run it from the repository root:
#
#     Rscript R/example.R
#
# The "weights" folder is found automatically. If you copy
# dnam_network_clock.R into your own project, either run from a directory that
# contains a "weights" folder, set options(dnam_clock.weights_dir = "..."), or
# pass weights_dir= to predict_age().

source("R/dnam_network_clock.R")

# Look at what the clock is.
info <- clock_info()
if (is.list(info)) {
  cat(sprintf("Clock metadata: K = %d PCs over %d modules (%d CpGs)\n",
              info$K, info$n_modules, info$n_cpgs))
  cat(sprintf("  Trained R2(test) = %.3f, MAE(test) = %.2f years\n",
              info$training_metrics$r2_test, info$training_metrics$mae_test))
}

# ---- The two lines that matter for your own data ----
# betas must be samples (rows) x CpG IDs (columns).
betas <- read.csv("examples/example_input.csv", row.names = 1, check.names = FALSE)
ages  <- predict_age(betas)
# -----------------------------------------------------

cat(sprintf("\nLoaded reference input: %d samples x %d CpGs\n",
            nrow(betas), ncol(betas)))
cat("Predictions:\n")
cat(sprintf("  range  : %.2f to %.2f years\n", min(ages), max(ages)))
cat(sprintf("  median : %.2f years\n", median(ages)))

# Check against the stored reference predictions (generated by the Python code).
expected <- read.csv("examples/expected_output.csv")
max_diff <- max(abs(ages - expected$predicted_age))
cat(sprintf("\n  max |predicted - expected| = %.2e   %s\n",
            max_diff, if (max_diff < 1e-6) "PASS" else "FAIL"))
